### ISSUE TITLE
[Authentication] Pem key instead of pass phrase ?

### ISSUE THREAD

**Issue by pixocode** [Edujugon/PushNotification#1]
Hi,

Is it possible to use PEM file instead of a pass phrase for APN authentication ?
(file path and file_get_contents don't work :/)

Thanks

**Comment by pixocode** [comment]
Sorry, it's probably a problem on my side

**Comment by pixocode** [comment]
To use a file instead of a pass phrase, use this:  
`$passfile = $this->config['passFile'];`  
`stream_context_set_option($ctx, 'ssl', 'local_pk', $local_key);`

**Comment by Edujugon** [comment]
@pixocode

I'll check and add that requested feature to the current package.

I'll implement it on September since I'm out of my country right now..

I'll get back to you once it's done.

**Comment by Edujugon** [comment]
@pixocode 
This package already works with pem file. You don't need to use a pass phrase.

Could you elaborate the issue you're facing?

**Comment by Edujugon** [comment]
This request has been added to the last released v2.1.2.
you may refer to the commit if required 3cba7c0756f0d100c73689c4e5bb9e009b2955ce
