### ISSUE TITLE
Not Compatible with Laravel 5.0/5.1

### ISSUE THREAD

**Issue by zanechua** [Edujugon/PushNotification#10]
Is this package meant to not be compatible with 5.0 or 5.1?

I see that you request for minimum version of illuminate/support to be 5.2 which should mean Laravel 5.2 and above?

>   Problem 1
    - Conclusion: remove laravel/framework v5.1.45
    - Conclusion: don't install laravel/framework v5.1.45
    - edujugon/push-notification v2.1.0 requires illuminate/support ^5.2 -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.4].
    - edujugon/push-notification v2.1.2 requires illuminate/support ^5.2 -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.4].
    - edujugon/push-notification v2.1.3 requires illuminate/support ^5.2 -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.4].
    - edujugon/push-notification v2.1.4 requires illuminate/support ^5.2 -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.4].
    - edujugon/push-notification v2.1.5 requires illuminate/support ^5.2 -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.4].
    - edujugon/push-notification v2.1.6 requires illuminate/support ^5.2 -> satisfiable by illuminate/support[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.4].
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.1.45
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.1.45
    - Installation request for laravel/framework (locked at v5.1.45, required as 5.1.*) -> satisfiable by laravel/framework[v5.1.45].
    - Installation request for edujugon/push-notification ^2.1 -> satisfiable by edujugon/push-notification[v2.1.0, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6].

**Comment by Edujugon** [comment]
@zanechua 
Hi,

Could you have a try with this branch [laravel-5](https://github.com/Edujugon/PushNotification/tree/laravel-5)

Update your composer like below:

`"edujugon/push-notification": "dev-laravel-5"`

Then

`composer update`

Let me know if that worked for you

**Comment by Edujugon** [comment]
@zanechua 

I've just tested on Laravel 5.0 and 5.1 and it works as expected. :)

**Comment by zanechua** [comment]
@Edujugon That works for me. Thanks for the speedy reply.

Might wanna add that into the docs?

**Comment by Edujugon** [comment]
@zanechua 

Glad to know it worked for you :)

Of course, I'll add it into the docs.
