### ISSUE TITLE
config/pushnotification settings not reflected when using Facade

### ISSUE THREAD

**Issue by Tribunal51** [Edujugon/PushNotification#104]
I have published the package's configuration file to my app's config directory, using: 
`php artisan vendor:publish --provider="Edujugon\PushNotification\Providers\PushNotificationServiceProvider" --tag="config"
`

However, when I try to use it in the Controller, after `use Edujugon\PushNotification\PushNotification`, when I create a new instance 
`$push = new PushNotification;`  the settings like apiKey in the config/pushnotification folder is not reflected here and I have to re-setup it manually using setApiKey(). Is this intended behavior or am I missing something? I want the common settings like apiKey inside config\pushnotifications.php to be reflected whenever I create new instances so I don't have to set up the config everytime.

**Comment by Edujugon** [comment]
Hi @Tribunal51 ,

Could you try to clear the config cache?

`php artisan config:clear `

**Comment by Edujugon** [comment]
Closing this issue since there is no udpate from the creator .

Feel free to reopen it if needed.
