### ISSUE TITLE
FCM/GCM Usage

### ISSUE THREAD

**Issue by zanechua** [Edujugon/PushNotification#11]
Sorry for having to create another issue so quick but i can't seem to utilise the package if I declare an instance of the facade.

```
$push = new PushNotification('fcm');

$push->setMessage([
    'notification' => [
        'title'=>'This is the title',
        'body'=>'This is the message',
        'sound' => 'default'
    ],
    'data' => [
        'extraPayLoad1' => 'value1',
        'extraPayLoad2' => 'value2'
    ]
])
->setDevicesToken('token'); 
```

Having the above code will throw the following error: 

>  [Symfony\Component\Debug\Exception\FatalThrowableError]                                    
  Call to undefined method Edujugon\PushNotification\Facades\PushNotification::setMessage()

**Comment by Edujugon** [comment]
@zanechua 

Notice that the above code is not using the facade so kindly confirm your use statement at the head of your class is something like this:

use Edujugon\PushNotification\PushNotification;

And no like this:

use Edujugon\PushNotification\Facades\PushNotification;

**Comment by Edujugon** [comment]
@zanechua 

If you prefer using Facade, you could do something like this:

```
PushNotification::setService('fcm')
                            ->setMessage([
                                 'notification' => [
                                         'title'=>'This is the title',
                                         'body'=>'This is the message',
                                         'sound' => 'default'
                                         ],
                                 'data' => [
                                         'extraPayLoad1' => 'value1',
                                         'extraPayLoad2' => 'value2'
                                         ]
                                 ])
                            ->setApiKey('Server-API-Key')
                            ->setDevicesToken(['deviceToken1','deviceToken2','deviceToken3'...])
                            ->send()
                            ->getFeedback();
```

**Comment by zanechua** [comment]
ah. It needs to import the class directly?

Usually when i define packagse, I usually just do

```
use PushNotification;
```

Does this not work here?

**Comment by Edujugon** [comment]
If you want to use Facade, you should set this statement:

`use Edujugon\PushNotification\Facades\PushNotification;`

As you already know, Facade provides a "static" interface to the class that is available in the application's service container.

Otherwise, if you prefer no to use Facade, then you have to set the below statement:

`use Edujugon\PushNotification\PushNotification;`

Let me know if the change made it works

**Comment by zanechua** [comment]
ah I see. Thanks @Edujugon !

I'll stick with the Pure Facade Method. Cheers!
