### ISSUE TITLE
Laravel 7 Support

### ISSUE THREAD

**Issue by BoyeMagnus** [Edujugon/PushNotification#111]

**Comment by vesper8** [comment]
`4.2.0` is not compatible with Laravel 7 due to `illuminate/notifications ~5.8 || ^6.0`

@Edujugon Could you please release a new version with Laravel 7 compatibility?

Thanks a lot!

**Comment by Edujugon** [comment]
Hi,
I've just released a new version (v4.3.0) supporting L7.

**Comment by vesper8** [comment]
thanks for the quick turnaround!
