### ISSUE TITLE
Can't send in iOS

### ISSUE THREAD

**Issue by nbastoWM** [Edujugon/PushNotification#12]
I've succeeded in sending notifications before but now I can't seem to make it work.

If I test it here: http://www.pushwatch.com/apns/ with my PEM file and a token, I successfully receive it. But using this package I can't. 
There's no $push->feedback->error and the function getFeedback() also shows success. 

My config 
```
'apn' => [
      'certificate' => __DIR__ . '/iosCertificates/certificate.pem',
      'passPhrase'  => '',
      'dry_run'     => true
  ]
```
Sending:
```
$push = new PushNotification('apn');

        $push->setMessage([
                    'aps' => [
                        'alert' => [
                            'title' => $data['title'],
                            'body'  => $data['description']
                        ],
                        'sound' => 'default'
                    ],
                    'extraPayLoad' => [
                        'type' => $data['type'],
                        'id'   => $data['id'],
                        'body' => $data['description']
                    ],
                ])
            ->setDevicesToken([$devicetoken])
            ->send();


        if(isset($push->feedback->error)){
            \Log::info('ERRO notificação ios - ' . $push->feedback->error);
        } else {
             \Log::info('Enviado com sucesso - ' . $devicetoken);
        }
```

My PEM file doesn't have a passPhrase, I tryed with and without the passPhrase line.

Am I missing something?

**Comment by Edujugon** [comment]
@nbastoWM

Could you send me your pem file and a token so that I can test it from my side?

If so, send it to edujugon@gmail.com

**Comment by Edujugon** [comment]
I'm closing this issue since it has already been solved as per our private conversation and it was related to apple certificates..

**Comment by scramatte** [comment]
Hi,

Same issue here (#121). Can you help?

Regards
