### ISSUE TITLE
.p12 instead of .pem

### ISSUE THREAD

**Issue by dantaylorseo** [Edujugon/PushNotification#13]
Not an issue per-se just a feature request. Is there any way you could modify this to use .p12 or .pem files?

It would just remove the extra step of generating the .pem

**Comment by Edujugon** [comment]
As far as I know you have to create a .pem file.
Anyway, I should have to research that. If you find a way, you are welcome to create a pull request or send me a message with the details.

**Comment by dantaylorseo** [comment]
It's ok now. I realised I've been using fastlane for my build and submit for a while and they have a certificate generator too. That generates pem files. 

Mark this as closed if you like?

Sent from my mobile device. 

Dan Taylor

**Comment by Edujugon** [comment]
Okay, closing it then :)
