### ISSUE TITLE
Android Push Notification suddenly stop working.

### ISSUE THREAD

**Issue by ZaffJa** [Edujugon/PushNotification#14]
![image](https://cloud.githubusercontent.com/assets/12205174/22329415/0eb53084-e3fc-11e6-814a-1cdafe1b7675.png)

I have not change anything at all. It just stop working. Before this it works like a charm. Maybe I'm missing something here...

```php
PushNotification::setService('fcm')
        ->setMessage([
            'notification' => [
                'title' => "hello",
                'body' => "haiii",
                'sound' => 'default'
            ],
            'data' => [
                'extraPayLoad1' => 'value1',
                'extraPayLoad2' => 'value2'
            ]
        ])
        ->setApiKey('My api key')
        ->setDevicesToken('My device token')
        ->send()
        ->getFeedback()
```

**Comment by Edujugon** [comment]
Hi,

Have you tried with another device token aside from that one of the example?

As per the attached response, it looks like firebase has not that device token anymore in its list.

One approach could be to uninstall the app and install it back again.

Let me know if you're facing the same issue after that.

**Comment by ZaffJa** [comment]
Thank you for the response. I register a new user and the push notifications are working again. It did not work for other device tokens aside from the newer ones. It is kind of strange that push service did not work for older device tokens now.
