### ISSUE TITLE
Installation issue with laravle9.2  

### ISSUE THREAD

**Issue by parthvora-tecocraft** [Edujugon/PushNotification#156]
![image](https://user-images.githubusercontent.com/71762330/165284836-0efb99b5-c332-43eb-8eca-f153df405e1d.png)

My php version is 8.0.8

Getting error on 
composer require edujugon/push-notification

 Root composer.json requires edujugon/push-notification ^5.0 -> satisfiable by edujugon/push-notification[v5.0.0].
    - edujugon/push-notification v5.0.0 requires illuminate/support ~5.8 || ^6.0 || ^7.0 || ^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by vidhimultiqos** [comment]
Have you solve this error?

**Comment by mahmoudebakers** [comment]
@Edujugon 
Have you Solve this error?

**Comment by vidhimultiqos** [comment]
Solution @parthvora-tecocraft : https://github.com/Edujugon/PushNotification/issues/157
