### ISSUE TITLE
Issue in Laravel 9.2

### ISSUE THREAD

**Issue by vidhimultiqos** [Edujugon/PushNotification#157]
`composer require edujugon/push-notification` is not installable in laravel 9.

my composer.json is as below
   

    "require": {
            "php": "^7.3|^8.0.0",
            "arcanedev/log-viewer": "^9.0",
            "brian2694/laravel-toastr": "^5.56",
            "doctrine/dbal": "^3.3",
            "guzzlehttp/guzzle": "^7.2",
            "kyslik/column-sortable": "^6.4",
            "laravel/framework": "^9.2",
            "laravel/passport": "*",
            "laravel/sanctum": "^2.14.1",
            "laravel/tinker": "^2.7",
            "laravel/ui": "^3.4",
            "league/flysystem-aws-s3-v3": "^3.0",
            "league/glide-laravel": "^1.0",
            "twilio/sdk": "^6.36",
            "vinkla/hashids": "^10.0"
        },

Error is below:

    Your requirements could not be resolved to an installable set of packages.
    
      Problem 1
        - Root composer.json requires edujugon/push-notification ^5.0 -> satisfiable by edujugon/push-notification[v5.0.0].
        - edujugon/push-notification v5.0.0 requires illuminate/support ~5.8 || ^6.0 || ^7.0 || ^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    
    You can also try re-running composer require with an explicit version constraint, e.g. "composer require edujugon/push-notification:*" to figure out if any version is installable, or "composer require edujugon/push-notification:^2.1" if you know which you need.
    
    Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by simha95** [comment]
@Edujugon, Any work around solution for the above issue?

**Comment by mahmoudebakers** [comment]
@Edujugon , any update for this issue ?

**Comment by vidhimultiqos** [comment]
No.

**Comment by Teglgaard** [comment]
I have just used an alternate version of it that I found in the pull requests. 
In composer.json

then input this and 
    "require": {
 "edujugon/push-notification": "*"
 },
"repositories": [
        {
            "url": "https://github.com/xHeinrich/PushNotification.git",
            "type": "vcs"
        }
    ]

**Comment by mahmoudIsProgramer** [comment]
excellent , worked for me  
thanks @Teglgaard

**Comment by vidhimultiqos** [comment]
Yes, @Teglgaard. Your given solution worked successfully but they asked for a GitHub token.

**Comment by m7md3omr** [comment]
I setup the package as local hosted package as following,


```
"require": {
        "edujugon/push-notification":"*"

},
 "autoload-dev": {
        "psr-4": {      
            "Edujugon\\PushNotification\\": "vendor/edujugon/push-notification/src/"

        }
    },
     "repositories": [
    {
    "url": "vendor/edujugon/push-notification",
    "type": "path"
    }
```

also you need to change values in vendor/edujugon/push-notification/composer.json, to fit with new laravel versions.

**Comment by Edujugon** [comment]
Hi guys,

I'm looking for someone that can help me maintain this package as I'm currently very busy. 

If any of you is willing to help, please send me a mail at edujugon@gmail.com. 

Thanks.
