### ISSUE TITLE
edujugonPushNotification  class not found

### ISSUE THREAD

**Issue by adnanmayo** [Edujugon/PushNotification#20]
classes and alias are added in config/app.php 

getting an error `edujugonPushNotification` class not found. my laravel version is 5.4

**Comment by Edujugon** [comment]
Hi @adnanmayo ,

Could you show the full error trace and the code where you're using the package?

Be sure you've put the use statement correctly on the top of your file..

**Comment by Edujugon** [comment]
I'm closing the issue since I don't get any feedback.

You may open it back if you're still facing any issue.
