### ISSUE TITLE
Sleeping process

### ISSUE THREAD

**Issue by efeferrari** [Edujugon/PushNotification#21]
I'm using PushNotification in a Laravel 5.2 <a href='https://laravel.com/docs/5.2/artisan'>Artisan Console</a>.

I have PushNotification in a common Helper and works fine, but when I execute in console "push:send", I recieve push notifications in my phone, but console process never completes. My push:send command code is:

```
<?php
namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\PushQueue;
use Edujugon\PushNotification\Facades\PushNotification;

class SendPush extends Command
{
    protected $signature = 'push:send';

    protected $description = 'Send Push';

    public function __construct()
    {
        parent::__construct();
    }

    public function handle()
    {
        $queue = PushQueue::where('send', 0)->get();
        
        if($queue)
        {
            foreach($queue as $push)
            {
                # iOS
                if($push->type == 2)
                {
                    $result = PushNotification
                        ::setService('apn')
                        ->setUrl(env('PUSH_IOS_URL'))
                        ->setMessage( [ 'aps' => json_decode($push->config) ] )
                        ->setDevicesToken( json_decode($push->token) )
                        ->send()
                        ->getFeedback()
                    ;
                    
                    echo "iOS\n";
                    print_r($result);
                    echo "/iOS\n";
                }
            }
        }
    }
}

```
My SetUrl value is ssl://gateway.push.apple.com:2195 and I'm using production certificates.
Console never do the "echo" lines

**Comment by Edujugon** [comment]
Hi @efeferrari ,

So what I understand is that the notification arrives, right?
The problem is that it doesn't output the text you wanna show.

Have you tried the below code to output:
```php
 $this->info('Display this on the screen');
```

If that wasn't the issue you are really facing, please let me know with more details.

**Comment by efeferrari** [comment]
Thath's rigth @Edujugon, notification arrives, but debuggin in APN.php class, the code sleeps in line 301:
```
$apns = stream_socket_client($this->feedbackUrl, $errcode, $errstr, 60, STREAM_CLIENT_CONNECT, $ctx);
```
stream_socket_client call waits forever and ever. I set timeout parameter to 5, but doesn't work either.

I'm running script in my localhost environment. I gonna try in a public webserver and check if something changes.

**Comment by Edujugon** [comment]
Yeah,
Have a try over the other web server and let me know if you're still facing the same issue. Then I'll test it from my side.

**Comment by efeferrari** [comment]
I try in public server and works fine! :smile: 
Maybe was a restriction from local connections to Feedback Apple Service or a PHP bug, but PushNotifications works like silk :+1: 

Greetings from Chile :chile:

**Comment by Edujugon** [comment]
Hi @efeferrari ,

Happy to hear that and thank you for your kind words!!

Enjoy the package ;)
