### ISSUE TITLE
sending topics messages

### ISSUE THREAD

**Issue by pouriabagheri** [Edujugon/PushNotification#23]
do you support topics and conditions ?

**Comment by Edujugon** [comment]
Hi @pouriabagheri ,
Could you provide more data and an example  so that I can see if it could be added in further releases?

**Comment by pouriabagheri** [comment]
Hi @Edujugon here is a [link](https://firebase.google.com/docs/cloud-messaging/android/topic-messaging) to FCM doc. I am looking for a way to send messages to users who are subscribed to a topic. instead of sending to individual devices. to my knowledge the current library is assuming there is always a need for device token. but with topic approach we don't include FCM token of the device. just the topic.
thanks

**Comment by Edujugon** [comment]
Hi @pouriabagheri ,

I'm working on that feature you requested. It's already available in dev branch.

Could you give it a try and let me know?

This is an example about how use it:

```php
$push = new PushNotification('fcm');
$response = $push->setMessage(['message'=>'Hello World'])
            ->setApiKey('YOUR-API-KEY')
            ->setConfig(['dry_run' => false])
            ->sendByTopic('dogs')
            ->getFeedback();
```

or with a condition:
```php
$push = new PushNotification('fcm');
$response = $push->setMessage(['message'=>'Hello World'])
            ->setApiKey('YOUR-API-KEY')
            ->setConfig(['dry_run' => false])
            ->sendByTopic("'dogs' in topics || 'cats' in topics",true)
            ->getFeedback();
```

**Comment by pouriabagheri** [comment]
Thanks this would be very handy.

**Comment by Edujugon** [comment]
@pouriabagheri  did you try it?
I'll add this new feature to the new release. Hopefully today :)

**Comment by Edujugon** [comment]
Hi @pouriabagheri ,

The las version (v2.2.0) has been already released and supports the feature you requested.

Enjoy :)

**Comment by pouriabagheri** [comment]
@Edujugon thank you for the great work.
