### ISSUE TITLE
Grouping notifications like whatsapp

### ISSUE THREAD

**Issue by carvemerson** [Edujugon/PushNotification#24]
Is it possible to group messages like whatsapp app?
If yes, how can I do it with FCM?

**Comment by Edujugon** [comment]
Hi @carvemerson ,
I'm not sure if I'm getting your point.
Could you please elaborate it a little bit? Or show an example...

**Comment by carvemerson** [comment]
I want something like this:

![screenshot_2015-02-01-19-40-04](https://user-images.githubusercontent.com/6718864/29787935-27f7c53a-8c07-11e7-83d4-c89484a54189.png)

**Comment by Edujugon** [comment]
Hi @carvemerson 
What you want is related to how handle the messages reception and no how sending messages.
If that's exactly what you are looking for, I can't help you with that :(

That's out of the package scope

**Comment by carvemerson** [comment]
Ok, Thanks!
