### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by efeferrari** [Edujugon/PushNotification#27]
Hello @Edujugon,

I getting Out Of Memory error sending push to iOS.

![image](https://user-images.githubusercontent.com/3068483/30441748-aeb48df0-9950-11e7-9e92-1e5a92937d48.png)

I tried with develop and production url of Apple, but is always same error.

PHP v5.6.30
edujugon/push-notification: v2.2.0

**Comment by Edujugon** [comment]
Hi @efeferrari 
Have you tried to test it in other environment?

**Comment by efeferrari** [comment]
I tried in local and development environments. In both, I set ini_set memory_limit to 1 GB.

**Comment by Drozes** [comment]
Same issue,  Any luck on finding a fix for this?

**Comment by efeferrari** [comment]
I try with a new iOS certificate and works fine, but it's still a bug get an "Out of memory" instead an "invalid certificate" :thinking:

**Comment by Edujugon** [comment]
Hi @efeferrari @Drozes ,
I'm really busy these days and I'm not able to check out this issue.

For now, as said @efeferrari , you can generate a new certificate and try with it. It's not the first time that generating a new certificate solves some issues..

**Comment by gl3nda85** [comment]
Hi also having this issue with a new cert, anyone find the issue?

**Comment by Edujugon** [comment]
Hi @gl3nda85 ,

Could you try to call `apnsFeedback()` method and see if it returns any token?
**Notice** that method returns a list of tokes that should be removed from the deviceToken list to send the notification.
Then, try again to send the notification.

Let me know if that helped

**Comment by danielz0** [comment]
Hi Edujugon,
I am experiencing kind of the same error: when trying to send pushes to APN the php starts consume memory, freezes and at the end I got "PHP Fatal error: Allowed memory....".
The feedback() method is not even called because all freezes on send().

Any clue?

Best,
Daniel

Laravel 5.2, PHP 7.0

**Comment by Edujugon** [comment]
Hi @danielz0 ,

In the next days I'll dig deeply into this issue. Would you share your certificate with me so I could do tests with that one as well? if so, send me a mail to [edujugon@gmail.com](mailto:edujugon@gmail.com)

In the meantime, have you tried to generate a new Certificate? most probably is Apple who is refusing the connection to its server..

**Comment by danielz0** [comment]
Maybe this will help you?

Strace:
`[pid 27958] 19:53:56 recvmsg(12, {msg_name(12)={sa_family=AF_NETLINK, pid=0, groups=00000000}, msg_iov(1)=[{"\24\0\0\0\3\0\2\0\244\253\25Z6m\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 20
[pid 27958] 19:53:56 close(12)          = 0
[pid 27958] 19:53:56 socket(PF_INET, SOCK_DGRAM, IPPROTO_IP) = 12
[pid 27958] 19:53:56 connect(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("17.188.135.152")}, 16) = 0
[pid 27958] 19:53:56 getsockname(12, {sa_family=AF_INET, sin_port=htons(40476), sin_addr=inet_addr("46.101.111.122")}, [16]) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("17.188.129.28")}, 16) = 0
[pid 27958] 19:53:56 getsockname(12, {sa_family=AF_INET, sin_port=htons(56513), sin_addr=inet_addr("46.101.111.122")}, [16]) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("17.188.137.23")}, 16) = 0
[pid 27958] 19:53:56 getsockname(12, {sa_family=AF_INET, sin_port=htons(40665), sin_addr=inet_addr("46.101.111.122")}, [16]) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("17.188.135.148")}, 16) = 0
[pid 27958] 19:53:56 getsockname(12, {sa_family=AF_INET, sin_port=htons(59539), sin_addr=inet_addr("46.101.111.122")}, [16]) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("17.188.130.23")}, 16) = 0
[pid 27958] 19:53:56 getsockname(12, {sa_family=AF_INET, sin_port=htons(56115), sin_addr=inet_addr("46.101.111.122")}, [16]) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("17.188.141.156")}, 16) = 0
[pid 27958] 19:53:56 getsockname(12, {sa_family=AF_INET, sin_port=htons(54942), sin_addr=inet_addr("46.101.111.122")}, [16]) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("17.188.135.26")}, 16) = 0
[pid 27958] 19:53:56 getsockname(12, {sa_family=AF_INET, sin_port=htons(37714), sin_addr=inet_addr("46.101.111.122")}, [16]) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_UNSPEC, sa_data="\0\0\0\0\0\0\0\0\0\0\0\0\0\0"}, 16) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_INET, sin_port=htons(0), sin_addr=inet_addr("17.188.130.157")}, 16) = 0
[pid 27958] 19:53:56 getsockname(12, {sa_family=AF_INET, sin_port=htons(43001), sin_addr=inet_addr("46.101.111.122")}, [16]) = 0
[pid 27958] 19:53:56 close(12)          = 0
[pid 27958] 19:53:56 socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 12
[pid 27958] 19:53:56 fcntl(12, F_GETFL) = 0x2 (flags O_RDWR)
[pid 27958] 19:53:56 fcntl(12, F_SETFL, O_RDWR|O_NONBLOCK) = 0
[pid 27958] 19:53:56 connect(12, {sa_family=AF_INET, sin_port=htons(2195), sin_addr=inet_addr("17.188.135.152")}, 16) = -1 EINPROGRESS (Operation now in progress)`

This *EINPROGRESS (Operation now in progress)* lasts couple of minutes depend on how big is the memory limit and results in:
`Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /default/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:59
Stack trace:
#0 {main}  
`

**Comment by danielz0** [comment]
Hi @Edujugon 
I think I found the problem which might be here https://github.com/reactphp/stream/issues/64
Let me know your thoughts.

Best,
Daniel

**Comment by Edujugon** [comment]
Hi @danielz0 ,
Thank you for your support, I really appreciate it :)

Have you tested it in PHP 7.1.4 or 7.0.18 ?  Does that work for you?

**Comment by danielz0** [comment]
Hi @Edujugon,
Didn't have time to test this in php7.1.4 nor in 7.0.18, but will do it next week, as I plan to update at least on of my servers. For now I am using self-written script which chunks data into smaller sets.

The payload which crashed in my case contains 1000tokens and one-two lines in the message body. 

Best,
Daniel

**Comment by Edujugon** [comment]
The new releases (3.x & 2.2.x) prevent of this error.
I'm closing this issue. feel free to open it again if the error persists.
