### ISSUE TITLE
When download app from app store (production) , push is not arriving

### ISSUE THREAD

**Issue by erjonhazizaj** [Edujugon/PushNotification#31]
When i was testing the push notification on development it works perfectly, but after I commit it on app store and downloaded it, push notification does not work, any idea what is wrong?
should the ios guy change the url for production 
  /**
     * Url for development purposes
     *
     * @var string
     */
    private $sandboxUrl = 'ssl://gateway.sandbox.push.apple.com:2195';

    /**
     * Url for production
     *
     * @var string
     */
    private $productionUrl = 'ssl://gateway.push.apple.com:2195';

    /**

**Comment by Edujugon** [comment]
Hi @erjonhazizaj ,

Make sure you changed your certificate to a production push SSL certificate..
