### ISSUE TITLE
Fake Message ID error

### ISSUE THREAD

**Issue by risnaa** [Edujugon/PushNotification#35]
I am new to Laravel and Pushnotification as well, I am using below code t send push notification

$respone = PushNotification::setService('fcm')
        ->setMessage([
            'notification' => [
                    'title'=>'Sheep App notofication',
                    'body'=>'A user try to contact you',
                    'sound' => 'default'
                    ]])
        ->setApiKey('AAAAxO2N17Q:APA91bGS5s7qy0larSwA0SOnz-5hv-Ls62hKJI3A5Q1ReKfgicl-aT2kB4hW-wpKt3sOV_q1rPGaWJRaKRv8tZ2rq99DTCq1ffqujKhsxOqObXjHTCGdzr2y8aBH_N9TZ874Mmx7IZux')
        ->setDevicesToken(['ewGx_pBcDzI:APA91bH1JQIpQyqsik5RM_wtAAkrCb035Vkh8DQxSuv6X2qr3QlooVb5-b_y1lB9x3Jk1i9URC9LjA2UgbrVWQmlYu82rrwKzfTNrDt7qGfkbR60lr3lNk3alAUWoANIQWe60linN96i'])
        ->send()
        ->getFeedback();

I am getting fake_message_id Error Please help me to solve the Issue.

**Comment by Edujugon** [comment]
Hi @risnaa ,

Make sure that your `dry_run` config parameter is false instead of true?

If that doesn't solve it, paste in here the full response message.
