### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by rajkumar-patidar** [Edujugon/PushNotification#37]
stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired in /vendor/edujugon/push-notification/src/Apn.php:184

**Comment by Edujugon** [comment]
Hi @rajkumar-patidar ,
As your message exposes, the issue is related to your certificate. it has expired.

**Comment by rajkumar-patidar** [comment]
Hello,
How i can disable this error using Config file when sending  IOS notification PHP terminate script and showing fatal error. Please how i can disable this error using config level?

**Comment by Edujugon** [comment]
In order to solved that issue, you should release a new certificate.
If that wasn't possible, maybe wrapping the send call in a try/catch you could handle the error so it wouldn't end up in a server error.
