### ISSUE TITLE
Schedule a notification for future delivery

### ISSUE THREAD

**Issue by arbabi2010** [Edujugon/PushNotification#39]
Hi , Is it possible to Schedule a notification for future delivery in android?

**Comment by Edujugon** [comment]
Hi @arbabi2010 ,
Sorry for my delay in reply.

There is no a built-in feature in this package that covers what you ask. But it's definitely a nice idea. I'll try to add it in future releases.

In the meanwhile, you can achieve it relatively easy. Create a Job class and when dispatching it just use the delay method.

Simple example:
```php
MyJob::dispatch()->delay(now()->addMinutes(10));
```

Hope that helps.

**Comment by arbabi2010** [comment]
Hi.
Tanx for your reply.
I wait for that.
and job is good idea for now.
tanx

**Comment by Umarjaved420** [comment]
Hi @Edujugon,
Is schedule push notification implemented or not in package,
I want to add reminder push notification in my project, so i need some suggestion and
Hi @arbabi2010, 
if you done this please let me know how to implement it.

Thanks in Advance

**Comment by Edujugon** [comment]
Hi @Umarjaved420 ,

I've been very busy these days and I couldn't find the time to add such feature.. So nop, it's not implemented yet.

Anyway, could you elaborate a bit more what you wanna achieve providing more details?

**Comment by Umarjaved420** [comment]
Hi @Edujugon ,
That's Ok and thanks for reply,
Actually i want to add **Reminder** feature in my project, according to requirement **user** set the time for reminder and will get push notification on set time,
Problem is to send push notification by get reminder time from database.

**Comment by Edujugon** [comment]
Hi @Umarjaved420 ,
You can achieve the same using jobs and delaying when dispatching. Have a look at my previous messages..

You can also [schedule a queued Job](https://laravel.com/docs/5.5/scheduling). In short, You create a job which is schedule for every minute. Such job check if there is any reminder to be sent. If so, send the notification..

Hope that helps.

**Comment by Umarjaved420** [comment]
Hi @Edujugon ,
Thanks i will try it definitely.

**Comment by Edujugon** [comment]
I'm closing this ticket since it's not a package issue actually.
Anyway, feel free to reopen it anytime if required.

Regards
