### ISSUE TITLE
stream_socket_client() error

### ISSUE THREAD

**Issue by Umarjaved420** [Edujugon/PushNotification#40]
Hi, i have question about APNS connection

ERROR
"success": false
"error": "Connection problem: stream_socket_client(): Unable to set local cert chain file `C:\xampp\htdocs\application_name\config/iosCertificates/aps_development.cer'; Check that your cafile/capath settings include details of your certificate and its issuer\r\n"

Thanks in Advance, please mention if irrelevant to package

**Comment by Edujugon** [comment]
Hi @Umarjaved420 ,
You must generate a *.pem file as certificate. Hope [this link](https://stackoverflow.com/questions/21250510/generate-pem-file-used-to-setup-apple-push-notification) helps.

**Comment by Umarjaved420** [comment]
Thanks for help @Edujugon ,
I have *.cer file for certificate. Isn't it work??

**Comment by Edujugon** [comment]
Nop, you must generate a .pem for that. check out the above link I gave you.

Let me know if face any other issue

**Comment by Umarjaved420** [comment]
sure, thanks for valuable suggestion

**Comment by Edujugon** [comment]
Hi @Umarjaved420 ,
I'm closing this since it's atually not an issue related to the package.

Anyway, feel free to reopen it if still face any issue :)
