### ISSUE TITLE
certificate issue 

### ISSUE THREAD

**Issue by vishal-bluesys** [Edujugon/PushNotification#43]
{"success":false,"error":"cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)"}

 $push=   PushNotification::setService('fcm')
                        ->setMessage([
                             'notification' => [
                                     'title'=>'This is the title',
                                     'body'=>'This is the message',
                                     'sound' => 'default'
                                     ],
                             'data' => [
                                     'extraPayLoad1' => 'value1',
                                     'extraPayLoad2' => 'value2'
                                     ]
                             ])
                       // ->setApiKey('Server-API-Key')
                        ->setDevicesToken(['dGwMZ7AiI-k:APA91bFBbw_gX48VYJGSw2MpEtz4hEZUd2occkvkzeR3NKMqNVipYxB4oWEBOlOU_aZU5IFnoPiN-pfZSv4VIUwIuL0eAt7UYl4wmz-LXTwJOmyvVztq7Fn0s6sTuil1_LcA82YKCE0-'])
                        ->send()
                        ->getFeedback();

**Comment by Edujugon** [comment]
Hi @vishal-bluesys ,

This is actually not a package issue..
Go through [this thread](https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate), I think it will help.

**Comment by Edujugon** [comment]
Closing this issue since there is no update from the creator.
