### ISSUE TITLE
Class 'App\Http\Controllers\PushNotification' not found

### ISSUE THREAD

**Issue by Rehmani3551** [Edujugon/PushNotification#44]
Class 'App\Http\Controllers\PushNotification' not found.

**Comment by Edujugon** [comment]
Hi @Rehmani3551 ,

You must add the use statement at the top of the Controller class.

```php
use Edujugon\PushNotification\PushNotification;
```

**Comment by Rehmani3551** [comment]
thanks Edujugon

**Comment by Edujugon** [comment]
Could you elaborate your question?
I'm not sure if I understand you correctly

**Comment by Edujugon** [comment]
Closing this issue since there is no update from the issue creator.
Feel free to reopen it if needed.
