### ISSUE TITLE
Is it possible to use p8 instead of pem file ? 

### ISSUE THREAD

**Issue by kpmessapps** [Edujugon/PushNotification#45]
How to use the p8 file with this library instead of pem file in APNS? 
How to set key_id, team_id, and app_bundle_id with this library for p8?

**Comment by Edujugon** [comment]
Hi @kpmessapps ,

You must first generate a pem file since the package expects that format..

**Comment by kpmessapps** [comment]
Okay, thank you @Edujugon .
And is there any chances to extend this library for p8 in near future? :)

**Comment by kpmessapps** [comment]
Okay, thank you @Edujugon .
And is there any chances to extend this library for p8 in near future? :)
