### ISSUE TITLE
setMessage not defined

### ISSUE THREAD

**Issue by dantaylorseo** [Edujugon/PushNotification#5]
Hi I am getting the following error:

`Call to undefined method Edujugon\PushNotification\Facades\PushNotification::setMessage()`

This is my code:

```
$push = new PushNotification('apn');
		$push->setMessage([
            'aps' => [
                'alert' => [
                    'title' => 'This is the title',
                    'body' => 'This is the body'
                ],
                'sound' => 'default'

            ],
            'extraPayLoad' => [
                'custom' => 'My custom data',
            ]
        ])
        ->setDevicesToken(['DEVICE_TOKEN_HERE']);
$push->send();
```

Also if I use the facade I get success code but no notifications received, any ideas?

**Comment by Edujugon** [comment]
Hello,
Notice that the showed code is not using the facade so kindly confirm your use statement at the head of your class is something like this:

use Edujugon\PushNotification\PushNotification;

And no like this:

use Edujugon\PushNotification\Facades\PushNotification;

**Comment by dantaylorseo** [comment]
Perfect thanks for that.

Now onto the last part... I get 

`stdClass Object ( [success] => 1 [failure] => 2 [tokenFailList] => Array ( [0] => deviceToken2 [1] => deviceToken3 ) )`

_I added the default device tokens to test errors_

So it looks like it's completing but no pushes are received. I have tried in dry run and prod. 

I am getting the deviceToken via:

```
func application(_ application: UIApplication,
            didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        
        var token: String = ""
        for i in 0..<deviceToken.count {
            token += String(format: "%02.2hhx", deviceToken[i] as CVarArg)
        }
        
        print("tokenString: \(token)")
            
    }
```

**Comment by Edujugon** [comment]
@dantaylorseo
After checking your details, I suggest you to check on the mobile app side. As you can see in the push service response, it shows 1 success which that token is the one you create. So the token is correct and for the push service provider the notification has been sent.

Maybe the app is not getting the notifications as expected. Did you check that yet?

**Comment by dantaylorseo** [comment]
@Edujugon If I use PushMeBaby to test the deviceToken I get the notifications from there using the same deviceToken and pem file.

**Comment by Edujugon** [comment]
Could you please show me the code what you're using to send the notification?

**Comment by dantaylorseo** [comment]
```
        $push = new PushNotification('apn');
		$push->setMessage([
            'aps' => [
                'alert' => "This just in!",
                'sound' => 'default'

            ],
            'extraPayLoad' => [
                'custom' => 'My custom data',
            ]
        ]);
		$push->setDevicesToken(['5a66cf3f8022a923fd7d8cf3503ca0dd91a1e26b187170e1497907188e542b5f']);
		$push->send();
```

**Comment by dantaylorseo** [comment]
@Edujugon strangely if I use the code below it works fine. I can't see much different from your code?

```
        $deviceToken = '5a66cf3f8022a923fd7d8cf3503ca0dd91a1e26b187170e1497907188e542b5f';

		$ctx = stream_context_create();
		stream_context_set_option($ctx, 'ssl', 'local_cert', config_path( 'iosCertificates/apns-dev-cert.pem' ) );

		// Open a connection to the APNS server
		$fp = stream_socket_client(
		  'ssl://gateway.sandbox.push.apple.com:2195', $err,
		  $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

		if (!$fp)
		  exit("Failed to connect: $err $errstr" . PHP_EOL);

		echo 'Connected to APNS' . PHP_EOL;

		// Create the payload body
		$body['aps'] = array(
		  'alert' => "Another test",
		  'sound' => 'default',
		  );

		// Encode the payload as JSON
		$payload = json_encode($body);

		// Build the binary notification
		$msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;

		// Send it to the server
		$result = fwrite($fp, $msg, strlen($msg));

		if (!$result)
		  echo 'Message not delivered' . PHP_EOL;
		else
		  echo 'Message successfully delivered' . PHP_EOL;

		// Close the connection to the server
		fclose($fp);
```

**Comment by Edujugon** [comment]
@dantaylorseo
Is the dry_run param sets as false in config file?

**Comment by dantaylorseo** [comment]
@Edujugon Yes

**Comment by Edujugon** [comment]
@dantaylorseo
Could I try from my side to send you a notification using the device token provided?

**Comment by dantaylorseo** [comment]
Yes

**Comment by Edujugon** [comment]
In order to send the test I'll need the certificate and the passPhrase.
Could you send it to edujugon@gmail.com?

By the way, in the above code you say it works, you're using the apple sandbox gateway. If the certificate you're using is for testing purposes, In this package you should update the config dry_run value to true.

Could you do a try with the mentioned changes?

**Comment by Edujugon** [comment]
It was an issue when assigning the proper gateway for apn. 
It has been fixed and it works as expected.

**Comment by dev2612** [comment]
@Edujugon sir aim getting this error please help exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Edujugon\PushNotification\PushNotification' not found' in

**Comment by maharajay** [comment]
@Edujugon sir aim getting this error please help exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Edujugon\PushNotification\PushNotification' not found' in

**Comment by dantaylorseo** [comment]
> @Edujugon sir aim getting this error please help exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Edujugon\PushNotification\PushNotification' not found' in

Use `use Edujugon\PushNotification\PushNotification;` at the top of your file
