### ISSUE TITLE
Unable to set private key

### ISSUE THREAD

**Issue by nicolascarelli** [Edujugon/PushNotification#52]
Hi Edu and congrats x your package;

I m getting this error  "response": {
        "success": false,
        "error": "Connection problem: stream_socket_client(): Unable to set private key file `/var/www/html/ws/config/iosCertificates/aps_development.pem'\n"
    }

The path to the to cert is ok.
The file has 644 permissions.

Thanks in advance.

**Comment by Edujugon** [comment]
Could you recheck that you're using a valid passphrase for that cert?
Also, could you show the config params for APN in config/pushnotification.php

**Comment by nicolascarelli** [comment]
@Edujugon you were right;
Now it's working
Thanks and congrats

**Comment by Edujugon** [comment]
Cool! 🎉
