### ISSUE TITLE
Feedback when using as notification channel

### ISSUE THREAD

**Issue by BoyeMagnus** [Edujugon/PushNotification#53]
How are you able receive feedback, when using a notification channel with ShouldQueue?

I've tried called getFeedback and getUnregisteredDeviceTokens after the request finished. But I receive either [] or NULL.
The notification is sent and received. I am using both a valid token and an invalid one. 

TestController file:
![image](https://user-images.githubusercontent.com/24491343/41511420-a7927672-7276-11e8-8cbe-b2572e08988c.png)

NewMessage file:
![image](https://user-images.githubusercontent.com/24491343/41511423-b69a33bc-7276-11e8-9933-73b8df8fb216.png)

Should I be calling getFeedback/getUnregisteredDeviceTokens another place?

**Comment by Edujugon** [comment]
Closing this since there is no feedback from the issue creator.
Feel free to reopen it anytime if needed.
