### ISSUE TITLE
GCM push notification is not receiving 

### ISSUE THREAD

**Issue by DineeshDS** [Edujugon/PushNotification#55]
Hi, 
I am first time using this package and this is perfect when am using push notification using APN, But now am trying with GCM added api token and device id but response seems there is no error. But not yet i dont receive any push.

use Edujugon\PushNotification\PushNotification;
Controller 
$push = new PushNotification();
        $push->setMessage([
        'notification' => [
                'title'=> 'Nithin push kittumbo para - android',
                'body'=> 'Nithin push kittumbo para - android',
                'sound' => 'default'
                ],
        'data' => [
                'extraPayLoad1' => 'value1',
                'extraPayLoad2' => 'value2'
                ]
        ])
        ->setApiKey('AAAAzNWar6k:APA91bFifq79w9hjoEnuwDv1swLhG0GM0_bim2gfDoJZmg0gwKwqmH6byd5fUcAwfPwWsfJJ4Vy0JO2Ajf0d6c-hW5y70SIelBr5POAJOUDuHWesz_Bt5HOsBoe3Kum')
        ->setDevicesToken(['APA91bGN-Ng4CaQyWqMfzcmu21kU-HWyLwIS8yoR2U7K_ZYRF6MS8ARqSkb3encMr2sxft8wtmZUbkrTUwZP0P8UURLwVgsLe3DU7UD-CjSvkPWMabKMGUXviTEjjfq4QLmqf7GtH6d5'])
        
                ->send();

pushnotification.php

return [
  'gcm' => [
      'priority' => 'normal',
      'dry_run' => true,
      'apiKey' => 'AAAAzNWar6k:APA91bFifq79w9hjoEnuwDv1swLhG0GM0_bim2gfDoJZmg0gwKwqmH6byd5fUcAwfPwWsfJJ4Vy0JO2Ajf0d6c-hW5y70SIelBr5POAJOUDuHWesz_Bt5HOsBoe3Kum',
  ],
  'fcm' => [
        'priority' => 'normal',
        'dry_run' => false,
        'apiKey' => 'My_ApiKey',
  ],
  'apn' => [
      'certificate' => __DIR__ . '/iosCertificates/SprightlyPushCert.pem',
      'passPhrase' => '1234', //Optional
      'passFile' => __DIR__ . '/iosCertificates/yourKey.pem', //Optional
      'dry_run' => false
  ]
];

**Comment by Edujugon** [comment]
Hi @DineeshDS ,
have you tried to set 'dry_run' to false in pushnotification.php/gcm config ?

**Comment by DineeshDS** [comment]
yes i have tried with dry_run false

**Comment by Edujugon** [comment]
Could you show me the feedback after sending the notification?
You just can get it using `getFeedback()` method

**Comment by DineeshDS** [comment]
This is the response 

#url: "https://android.googleapis.com/gcm/send"
    #config: array:3 [
      "priority" => "normal"
      "dry_run" => false
      "apiKey" => "AAAAzNWar6k:APA91bFifq79w9hjoEnuwDv1swLhG0GM0_bim2gfDoJZmg0gwKwqmH6byd5fUcAwfPwWsfJJ4Vy0JO2Ajf0d6c-hW5y70SIelBr5POAJOUDuHWesz_Bt5HOsBoe3Kum"
    ]
    #feedback: {#6372
      +"multicast_id": 7028173908884911686
      +"success": 1
      +"failure": 0
      +"canonical_ids": 0
      +"results": array:1 [
        0 => {#6335
          +"message_id": "0:1530786565588271%7b6555eff9fd7ecd"
        }
      ]
    }
  }
  #servicesList: array:3 [
    "gcm" => "Edujugon\PushNotification\Gcm"
    "apn" => "Edujugon\PushNotification\Apn"
    "fcm" => "Edujugon\PushNotification\Fcm"
  ]
  -defaultServiceName: "gcm"
  #deviceTokens: array:1 [
    0 => "APA91bGN-Ng4CaQyWqMfzcmu21kU-HWyLwIS8yoR2U7K_ZYRF6MS8ARqSkb3encMr2sxft8wtmZUbkrTUwZP0P8UURLwVgsLe3DU7UD-CjSvkPWMabKMGUXviTEjjfq4QLmqf7GtH6d5"
  ]
  #message: array:2 [
    "notification" => array:3 [
      "title" => " test"
      "body" => "test"
      "sound" => "default"
    ]
    "data" => array:2 [
      "extraPayLoad1" => "value1"
      "extraPayLoad2" => "value2"
    ]
  ]

**Comment by Edujugon** [comment]
After checking the above info, I can say that the notification was sent you.
This is the GCM message id confirming it was sent out successfully: 0:1530786565588271%7b6555eff9fd7ecd

Now, I would recommend to check your client implementation and confirm that it's really getting the notifications.

**Comment by DineeshDS** [comment]
Yeah, I have check with my client device , but push notification is not getting, We have tried  https://www.pushwatch.com/gcm/  with same api key and device id at that time getting notification.

**Comment by Edujugon** [comment]
are you using the same message structure as the package use? could you paste here the message you're sending through pushwatch?

The notification feedback is provide by the notification provider, so in this case by GCM server, and its response is successfully. I just can think of there could be some differences between the messages structure.

**Comment by DineeshDS** [comment]
Yes, sure

$push = new PushNotification();
        $push->setMessage([
        'notification' => [
                'title'=>'This is the title',
                'body'=>'This is the message',
                'sound' => 'default'
                ],
        'data' => [
                'extraPayLoad1' => 'value1',
                'extraPayLoad2' => 'value2'
                ]
        ])
        ->setApiKey('AAAAzNWar6k:APA91bFifq79w9hjoEnuwDv1swLhG0GM0_bim2gfDoJZmg0gwKwqmH6byd5fUcAwfPwWsfJJ4Vy0JO2Ajf0d6c-hW5y70SIelBr5POAJOUDuHWesz_Bt5HOsBoe3Kum_O0sRiLbvIcZX')
        ->setDevicesToken(['APA91bGN-Ng4CaQyWqMfzcmu21kU-HWyLwIS8yoR2U7K_ZYRF6MS8ARqSkb3encMr2sxft8wtmZUbkrTUwZP0P8UURLwVgsLe3DU7UD-CjSvkPWMabKMGUXviTEjjfq4QLmqf7GtH6'])
        ->send();

**Comment by Edujugon** [comment]
I asked for the message you are sending via pushwatch :)

Since the notification response is successful, I just can think of the messages format don't match..

Could you debug the notification in your client app? just if receives something, log it. if you do so, do you see something in the log?

**Comment by DineeshDS** [comment]
Sorry , In the client side they can only read those message which send from pushwatch, Client is a Xamarin mobile app, They reporting that they cant access log or message structure

**Comment by Edujugon** [comment]
Could you try to send the notification like below:
```php
$push->setMessage([
           'title'=>'This is the title',
           'body'=>'This is the message'
       ]);
```

**Comment by Edujugon** [comment]
Hi @DineeshDS ,
Any luck with my previous message?

**Comment by DineeshDS** [comment]
No, Status is same, Push triggering from my side , But not receiving in client side

**Comment by cosecantt** [comment]
$push = new PushNotification('fcm');

        $push->setMessage([
                'title'=>'This is the title',
                'body'=>'This is the message'
            ])
            ->setApiKey(env('GOOGLE_FCM_KEY', false))
            ->setDevicesToken('f2_OPr9e5c4:APA91bHnw6e9NHm3z6bTo0pI0swdjas9h4P9uEgincvyNS0UXPHx071ZIyh3MmJvAjMm3yOYRh4-y16BrsqB08Zw9fzwxiBCDH9BSNuqsRQsikNVq-NRiLlqf4PM_03gA_BMkbNHFgUEy3agGf4s35Af4MlDBAWxKg')
            ->send()

Above sends the message successfully but crashes my app.

Following sends message successfully and the notifications appears on the same app normally.

        $url = "https://fcm.googleapis.com/fcm/send";
        $token = "f2_OPr9e5c4:APA91bHnw6e9NHm3z6bTo0pI0swdjas9h4P9uEgincvyNS0UXPHx071ZIyh3MmJvAjMm3yOYRh4-y16BrsqB08Zw9fzwxiBCDH9BSNuqsRQsikNVq-NRiLlqf4PM_03gA_BMkbNHFgUEy3agGf4s35Af4MlDBAWxKg";
        $serverKey = env('GOOGLE_FCM_KEY', false);
        $title = "Title";
        $body = "Body of the message";
        $notification = array('title' =>$title , 'text' => $body, 'sound' => 'default', 'badge' => '1');
        $arrayToSend = array('to' => $token, 'notification' => $notification,'priority'=>'high');
        $json = json_encode($arrayToSend);
        $headers = array();
        $headers[] = 'Content-Type: application/json';
        $headers[] = 'Authorization: key='. $serverKey;
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);

        curl_setopt($ch, CURLOPT_CUSTOMREQUEST,"POST");
        curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
        curl_setopt($ch, CURLOPT_HTTPHEADER,$headers);
        //Send the request
        $response = curl_exec($ch);
        //Close request
        if ($response === FALSE) {
            die('FCM Send Error: ' . curl_error($ch));
        }
        curl_close($ch);


Any issues?
Thanks.

**Comment by DineeshDS** [comment]
@Edujugon issue with push notification is solved , we have implemented FCM in client side. Thank you

**Comment by Edujugon** [comment]
@DineeshDS cool!
Happy to hear that :)
