### ISSUE TITLE
Tag a release from master with the badge method

### ISSUE THREAD

**Issue by tomvo** [Edujugon/PushNotification#59]
It seems the `->badge()` method on the `Messages\PushNotification` class is only available in `dev-master`, can you tag a release for this?

**Comment by Edujugon** [comment]
Hi @tomvo ,

I've just created a [new release](https://github.com/Edujugon/PushNotification/releases/tag/v3.0.2) covering badge feature.

Thank you :)

**Comment by tomvo** [comment]
@Edujugon That's fast, thanks a lot!
