### ISSUE TITLE
Unable to set local cert chain file

### ISSUE THREAD

**Issue by allroundexperts** [Edujugon/PushNotification#62]
Hi, I'm getting this error consistently.
Connection problem: stream_socket_client(): Unable to set local cert chain file `/var/www/public_html/niggle/config/iosCertificates/niggle_push.pem'; Check that your cafile/capath settings include details of your certificate and its issuer.

I can connect to apns server when I add -CAfile entrust-2048-ca.cer to the open ssl command on my local environment.Please help.

**Comment by allroundexperts** [comment]
Don't you think that adding this: 
stream_context_set_option($ctx, 'ssl', 'cafile', path-to-ca-file)
to the apn.php file will solve the issue ?

**Comment by Edujugon** [comment]
Hi @allroundexperts ,

Could you try to give permissions to your .pem file?

Also, have a look at [this post](https://stackoverflow.com/a/5168358/6178015).

Let me know if that helps

**Comment by allroundexperts** [comment]
Thanks a lot!

**Comment by Edujugon** [comment]
Happy to know it helped :)
