### ISSUE TITLE
bug in getFeedback()

### ISSUE THREAD

**Issue by mohammad-mazraeshahi** [Edujugon/PushNotification#63]
hi @Edujugon

In getFeedback (), the return value of the multicast_id is double, for example, 7.20839961657612e + 18, which is the wrong value.

Please change multicast_id to string:

```
class Gcm extends PushService implements PushServiceInterface
{
public function send(array $deviceTokens,array $message)
    {
        $fields = $this->addRequestFields($deviceTokens,$message);
        $headers = $this->addRequestHeaders();
        try
        {
            $result = $this->client->post(
                $this->url,
                [
                    'headers' => $headers,
                    'json' => $fields,
                ]
            );

            $json = $result->getBody();

          //here changed
          //old code $this->setFeedback(json_decode($json));
             $this->setFeedback(json_decode($json , false , 512 , JSON_BIGINT_AS_STRING));

            return $this->feedback;

        }catch (\Exception $e)
        {
            $response = ['success' => false, 'error' => $e->getMessage()];
            
            $this->setFeedback(json_decode(json_encode($response), FALSE));

            return $this->feedback;
        }
    }
}
```

**Comment by Edujugon** [comment]
Hi @mohammad-mazraeshahi ,

I'm not sure if I'm getting your point.

Are you suggesting to replace this:
```php
$this->setFeedback(json_decode($json));
```
to this:
```php
$this->setFeedback(json_decode($json , false , 512 , JSON_BIGINT_AS_STRING));
```

**Comment by mohammad-mazraeshahi** [comment]
I will record all FCM returns.
I'm sure there is a need for this change.
Please apply this change:

`$this->setFeedback(json_decode($json , false , 512 , JSON_BIGINT_AS_STRING));
`

**Comment by Edujugon** [comment]
Could you please elaborate a bit more the issue you're facing?

The code change you're suggesting seems to use the default parameters in json_decode function. Isn't that exactly the same as the current code?

Could you provide an example of the output with both codes?

Thank you.

**Comment by mohammad-mazraeshahi** [comment]
![tempsnip png](https://user-images.githubusercontent.com/11412436/47584354-fed40700-d966-11e8-9653-917722873561.jpg)


As shown in the above image, the multicast_id return value is a very large number
The json_decode () function converts this value to a number such as the following number
6.26174813181673e+48

By inserting the following code, the amount is converted to String and prevents this from happening
`$this->setFeedback(json_decode($json , false , 512 , JSON_BIGINT_AS_STRING));`

output: multicast_id: "6261748131816737148"

**Comment by Edujugon** [comment]
Could you `dd` that `$json` before calling the json_decode ? I think that "number" (6.26174813181673e+48) is already there. So there is nothing about the json_decode function.

Let me know the result

**Comment by mohammad-mazraeshahi** [comment]
Show your code output using by Xdebug:
![tempsnip1 png](https://user-images.githubusercontent.com/11412436/48062428-42d0d280-e1d7-11e8-92e2-7ed76522b6d7.jpg)

Output with the following changes:
$this->setFeedback(json_decode($json , false , 512 , JSON_BIGINT_AS_STRING));

![tempsnip2 png](https://user-images.githubusercontent.com/11412436/48065248-70217e80-e1df-11e8-83d8-cdca8ecad699.jpg)

**Comment by Edujugon** [comment]
Hi @mohammad-mazraeshahi ,

Thank you for the provided information. I'm gonna create a new package version fixing this issue.

Shall I update you when released.

**Comment by Edujugon** [comment]
Hi @mohammad-mazraeshahi ,

I've just released a new package version(v3.0.5) which should fix this issue.

Thanks again for reporting it and providing detailed information.

**Comment by mohammad-mazraeshahi** [comment]
There is also a problem posting to the topic. Please change the file below:

**Comment by Edujugon** [comment]
Hey @mohammad-mazraeshahi ,

Thanks again for noticing that. I've just released a new package version that fixes the issue.
