### ISSUE TITLE
Using with Laravel Queue

### ISSUE THREAD

**Issue by ralph144** [Edujugon/PushNotification#64]
When i try to send push with queue - get next error "Trying to get property of non-object"
`$push = new PushNotification('fcm');`
`$push->setMessage(['notification' => $this->getNotification(), 'data' => $this->getData()])->setDevicesToken($this->getTokens())->send();`

**Comment by Edujugon** [comment]
Could paste here the whole error message?

**Comment by ralph144** [comment]
That's црфе I can get from feedback:
`['success' => false, 'error' => 'Trying to get property of non-object']`
If I send a push synchronously - everything is fine
