### ISSUE TITLE
FCM is not sending push for Web

### ISSUE THREAD

**Issue by shihabshahriar** [Edujugon/PushNotification#69]
Hello edujugon,

can you please check the web notification via fcm , i think it is not working.

Thanks in advance

**Comment by Edujugon** [comment]
Hi @shihabshahriar

Could you provide me with any code snippet and error message you're getting?

**Comment by shihabshahriar** [comment]
hi,

please see the attachment
it is saying success but ,not getting the push in browser.

<img width="493" alt="screenshot 2018-11-17 at 4 41 01 pm" src="https://user-images.githubusercontent.com/1762788/48660177-a8e71080-ea87-11e8-915f-806d41f0ad6b.png">

**Comment by shihabshahriar** [comment]
It is working , ignore it please.

**Comment by oscardias** [comment]
Hi @shihabshahriar , I'm having the same issue, do you remember what was the problem? Thanks!
