### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by mirazzaq** [Edujugon/PushNotification#77]
I am getting the following error while creating object, I can not trace why this error is generating.

<img width="1250" alt="screenshot 2019-01-25 at 2 43 03 pm" src="https://user-images.githubusercontent.com/9442077/51737876-8d177080-20af-11e9-96fd-121dca834a1e.png">

    {
        if (function_exists('config_path') &&
            file_exists(config_path('pushnotification.php')) &&
            function_exists('app')
        ) {
            $configuration = app('config')->get('pushnotification');
        } else {
            $configuration = include(__DIR__ . '/Config/config.php');
        }
        if (!array_key_exists($service, $configuration)) {
            throw new PushNotificationException("Service '$service' missed in config/pushnotification.php");
        }
        return $configuration[$service];
    }
 
    /**
     * Initialize the feedback array
     * @return array
     */
    protected function initializeFeedback()
    {

> "array_key_exists() expects parameter 2 to be array, null given"

**Comment by Edujugon** [comment]
Hi @mirazzaq ,

Did you run the following command:

```
php artisan vendor:publish --provider="Edujugon\PushNotification\Providers\PushNotificationServiceProvider" --tag="config"
```

**Comment by mirazzaq** [comment]
The issue happen when I run this command.

Though I have copied the files from another of my project and is now working properly.

**Comment by mirazzaq** [comment]
Yes please close is.

**Comment by MoaizP** [comment]
Please tell how to resolve this issue ?

**Comment by MoaizP** [comment]
@mirazzaq I also facing the same issue. I use this library in other project it worked fine but it create this error how to resolve this issue Please tell
