### ISSUE TITLE
array_key_exists() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by MoaizP** [Edujugon/PushNotification#81]
i am getting the following error . i can not trace why this error is generating. i am using this library for push notification in other project it worked but it shows that error in other. Please help. 
![xcvv](https://user-images.githubusercontent.com/48024263/53426653-2caa8480-3a09-11e9-8f57-feed51ab0b43.PNG)

    public function initializeConfig($service)
    {
        if (function_exists('config_path') &&
            file_exists(config_path('pushnotification.php')) &&
            function_exists('app')
        ) {
            $configuration = app('config')->get('pushnotification');
        } else {
            $configuration = include(__DIR__ . '/Config/config.php');
        }

        if (!array_key_exists($service, $configuration)) {
            throw new PushNotificationException("Service '$service' missed in config/pushnotification.php");
        }
        return $configuration[$service];
    }

**Comment by MoaizP** [comment]
If i use this piece of code from our previous project it worked not giving error. this is the code.

    public function initializeConfig($service)
    {
        if (function_exists('config_path') && file_exists(config_path('pushnotification.php'))) {
            $configuration = include(config_path('pushnotification.php'));
        } else {
            $configuration = include(__DIR__ . '/Config/config.php');
        }

        if (!array_key_exists($service, $configuration)) {
            throw new PushNotificationException("Service '$service' missed in config/pushnotification.php");
        }
        return $configuration[$service];
    }

**Comment by Edujugon** [comment]
Hi @MoaizP
Did you publish the `pushnotification.php` config file?

**Comment by MoaizP** [comment]
Hi @Edujugon 
yes i publish. with the help of this command
php artisan vendor:publish --provider="Edujugon\PushNotification\Providers\PushNotificationServiceProvider" --tag="config"

**Comment by Edujugon** [comment]
What Laravel version are you using?

Could you confirm the pushnotification.php config file was created?

**Comment by MoaizP** [comment]
Using laravel version 5.6.39 
yes file is created.

**Comment by Edujugon** [comment]
Could run the below command and try again? 

php artisan config:cache

**Comment by Edujugon** [comment]
Hey @MoaizP

Did you try the above command? I believe that should fix your issue

**Comment by MoaizP** [comment]
Hey @Edujugon 
Yes issue is resolved. You can close this issue.
