### ISSUE TITLE
Does not work "NotRegistered"

### ISSUE THREAD

**Issue by yelnyaface** [Edujugon/PushNotification#83]
I can send firebase push notification with my 'Server key' and 'Device Token' Directly from Firebase  cloud message panel as well as http://pushtry.com/

but when I try it with localhost and testing server I always get  ""NotRegistered"

is your plugin broken?

I am using this, and it Never work:

        $test = PushNotification::setService('fcm')
            ->setUrl('https://fcm.googleapis.com/fcm/send')
            ->setMessage([
                'notification' => [
                    'title'     =>'This is the title',
                    'body'      =>'This is the message',
                    'priority'  => 'high'
                ]
            ])
            ->setApiKey('apikey')
            ->setDevicesToken('1 token')
                        ->send()
        ->getFeedback();

        dd($test);

**Comment by yelnyaface** [comment]
I am using laravel 5.5 and "edujugon/push-notification": "^3.0",

**Comment by Edujugon** [comment]
Hi,

Could you provide the full response message from the feedback?

**Comment by Edujugon** [comment]
Closing issue since there is no response from the issue creator.
Feel free to re-open it if necessary.
