### ISSUE TITLE
Not showing when the App is open

### ISSUE THREAD

**Issue by BrunoCamarda** [Edujugon/PushNotification#84]
My app only show a push if it is in background. When i'm using the app, the push is not shown.

On  Log, the getFeedback() returns a success case.

So, my question is: is this the expected?

**Comment by Edujugon** [comment]
If the logs returns success, it means that the notification was sent out, I would check the client app and how to handle those notifications on those different cases..

**Comment by BrunoCamarda** [comment]
Ok. Thanks! ^_^
